
language: python
python:
  - "3.8"
branches:
  only:
    - master

install:
  - pip install cyclonedx-bom

script:
  - cyclonedx-py -i requirements.txt -o sbom.cdx.json

after_success:
  - git config --local user.email "hayasam@najah.edu"
  - git config --local user.name "hayasam"
  - git add sbom.cdx.json
  - git commit -m "Add SBOM [ci skip]" || echo "No changes to commit"
  - git push "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" HEAD:master
