language: python
jobs:
  include:
    - name: "Python 3.8 on Xenial linux"
      python: 3.8
      os: linux
      dist: xenial
      arch: amd64
    
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH # command to install dependencies
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install --upgrade setuptools wheel   # for some projects upgrading setuptools are needed
  - pip3 install .
script:
  - travis_wait 80 python3 example.py || travis_wait 80 python example.py  # running the example script.

after_success:
  - echo "Successfull."
