# .github/workflows/sbom.yml
name: Generate SBOM (Syft)

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate JSON SBOM
        uses: CycloneDX/gh-python-generate-sbom@v2
        with:
          input: ./requirements.txt
          output: ./sbom.cdx.json
          format: json
          
      - name: Upload SBOM files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-files
          path: |
            sbom.cdx.json
            
      - name: Commit SBOM to Repository
        run: |
          git config --local user.email "hayasam@najah.edu"
          git config --local user.name "hayasam"
          git add sbom.cdx.json
          git commit -m "Add SBOM"
       
       
