name: Python Build and SBOM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Python 3.8 Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: sudo apt-get update 

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install numpy==1.24.4  # Replace with suitable version
          pip install --prefer-binary -r requirements.txt
          pip install .


      # - name: Run example script
      #   run: |
      #     python example.py

      - name: Report success
        if: success()
        run: echo "Successfull."

  sbom:
    name: SBOM Generation
    runs-on: ubuntu-latest
    needs: build  # ensures SBOM is generated only after a successful build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM (CycloneDX + SPDX)
        run: |
          syft dir:. -o cyclonedx-json > sbom.cdx.json
          syft dir:. -o spdx-json > sbom.spdx.json

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-files
          path: |
            sbom.cdx.json
            sbom.spdx.json
