name: Python Build with SBOM

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and Generate SBOM
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade setuptools wheel
          pip install .

      - name: ▶️ Run your project
        run: |
          python3 example.py || python example.py

      - name: 🧾 Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: 🧮 Generate SBOM (CycloneDX + SPDX)
        run: |
          syft dir:. -o cyclonedx-json > sbom.github.json
          syft dir:. -o spdx-json > sbom.spdx.json

      - name: ⬆️ Upload SBOM files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-github
          path: |
            sbom.github.json
            

      - name: ✅ Report success
        if: success()
        run: echo "✅ Build and SBOM generation successful."
