# .github/workflows/sbom.yml
name: Generate SBOM (Syft)

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # تثبيت Syft بالإصدار المحدّد
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
            | sh -s -- -b /usr/local/bin

      # توليد ملف SBOM بصيغة CycloneDX-JSON
      - name: Generate SBOM
        run: syft packages dir:. -o cyclonedx-json --file sbom_github.json

      # رفع المخرجات كـ Artifact
      - uses: actions/upload-artifact@v4
        with:
          name: sbom-github
          path: sbom_github.json
