# .github/workflows/sbom.yml
name: Generate SBOM (Syft)

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate JSON SBOM
        uses: CycloneDX/gh-python-generate-sbom@v2
        with:
          path: .
          out: ./artifacts/sboms
          json: true
          github-bearer-token: ${{ secrets.GITHUB_TOKEN }}
