# .github/workflows/sbom.yml
name: Generate SBOM (Syft)

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Python SBOM
      - uses: CycloneDX/gh-python-generate-sbom@v2
        with:
          input: ./requirements.txt
          output: ./bom.json
          format: json
      # رفع المخرجات كـ Artifact
      - uses: actions/upload-artifact@v4
        with:
          name: sbom-github
          path: sbom_github.json
